[package]
name = "ddc-hi"
version = "0.0.1"
authors = ["arcnmx"]
build = "build.rs"

description = "High level DDC/CI monitor control"
keywords = ["ddc", "mccs", "vcp", "vesa"]

documentation = "http://arcnmx.github.io/ddc-hi-rs/ddc_hi"
repository = "https://github.com/arcnmx/ddc-hi-rs"
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "arcnmx/ddc-hi-rs" }
maintenance = { status = "passively-maintained" }

[dependencies]
ddc = "^0.1.0"
edid = "^0.2.0"
mccs = "^0.1.0"
mccs-caps = "^0.1.0"
mccs-db = "^0.1.1"
failure = "^0.1.1"

[target.'cfg(unix)'.dependencies]
ddc-i2c = { version = "^0.1.0", features = ["with-linux", "with-linux-enumerate"], optional = true }

[target.'cfg(windows)'.dependencies]
ddc-winapi = { version = "^0.1.0", optional = true }
nvapi = { version = "~0.0.4", default-features = false, features = ["i2c"], optional = true, git = "https://github.com/arcnmx/nvapi-rs.git" }

[features]
default = ["ddc-i2c", "ddc-winapi", "nvapi"]
